FROM node:latest as builder
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "start"]

FROM kanishk1497/multi-nginx:latest
WORKDIR '/app'
COPY . .

FROM nginx
EXPOSE 3000

